version: '3'

services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports: 
      - 56379:6379
    volumes:
      - ./.data/redis:/data

  bot:
    image: chat-superviser-bot:latest
    restart: unless-stopped
    build:
      context: .
    environment:
      # mandatory ENVs
      - API_ID
      - API_HASH
      - BOT_TOKEN
      # optional ENVs
      - CHECK_ONLY_FORWARDED_MESSAGES
      - CHECK_LINKS
      - DUPLICATE_SIMILARITY_THRESHOLD
      - MESSAGE_LENGTH_WORDS_THRESHOLD
      - RECENT_MESSAGES_AMOUNT
      - SELF_DESTRUCTION_MULTIPLIER
      - LOG_LEVEL
    tty: true
